import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Rubik_Doodle_Shadow } from "next/font/google";
import TopLoader from "@/components/TopLoader";

const inter = Inter({ subsets: ["latin"] });
const rubik = Rubik_Doodle_Shadow({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-rubik",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${rubik.variable}`}>
        <TopLoader />
        {children}
      </body>
    </html>
  );
}
